name: Gwydion CI/CD

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Build Jester
      run: |
        cd jester
        cargo build --release
    
    - name: Upload JVM module artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jvm-modules
        path: |
          */build/libs/*-jvm.jar
          !compiler/build/libs/*-jvm.jar
    
    - name: Upload compiler artifacts
      uses: actions/upload-artifact@v3
      with:
        name: compiler
        path: |
          compiler/build/libs/gwydion.jar
          compiler/build/bin/linuxX64/releaseExecutable/compiler.kexe
          compiler/build/bin/windowsX64/releaseExecutable/compiler.exe
    
    - name: Upload Jester artifact
      uses: actions/upload-artifact@v3
      with:
        name: jester
        path: jester/target/release/jester

  pre-release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    
    - name: Display structure of downloaded files
      run: ls -R
    
    - name: Generate release tag
      id: tag
      run: |
        echo "release_tag=release-$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Create pre-release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          compiler/gwydion.jar
          compiler/compiler.kexe
          compiler/compiler.exe
          jester/jester
        prerelease: true
        tag_name: ${{ steps.tag.outputs.release_tag }}
        name: Pre-release ${{ steps.tag.outputs.release_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        tag_name: ${{ github.sha }}
        name: Pre-release ${{ github.sha }}

